# Generated by Django 5.2.1 on 2025-05-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
